#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook 'sprout-ruby',
  :github => 'pivotal-sprout/sprout-ruby'

cookbook 'sprout-base',
  :github => 'pivotal-sprout/sprout-base'

cookbook 'sprout-osx-apps',
  :github => 'https://github.com/tb021781/sprout-osx-apps'

cookbook 'sprout-osx-settings',
  :github => 'https://github.com/tb021781/sprout-osx-settings'

cookbook 'osx',
  :github => 'pivotal-sprout/osx'

cookbook 'sprout-rubymine',
  :github => 'pivotal-sprout/sprout-rubymine'

cookbook 'sprout-homebrew',
  :github => 'https://github.com/tb021781/sprout-homebrew'

cookbook 'sprout-terminal',
  :github => 'pivotal-sprout/sprout-terminal'
