#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook 'sprout-ruby',
  :github => 'pivotal-sprout/sprout-ruby'

cookbook 'sprout-base',
  :github => 'pivotal-sprout/sprout-base'

cookbook 'sprout-osx-apps',
  :github => 'tbiethman/sprout-osx-apps'

cookbook 'sprout-osx-settings',
  :github => 'tbiethman/sprout-osx-settings',
  :ref => 'test_config'

cookbook 'osx',
  :github => 'pivotal-sprout/osx'

cookbook 'sprout-rubymine',
  :github => 'pivotal-sprout/sprout-rubymine'

cookbook 'sprout-homebrew',
  :github => 'tbiethman/sprout-homebrew'

cookbook 'sprout-terminal',
  :github => 'pivotal-sprout/sprout-terminal'

cookbook 'sprout-ssh',
  :github => 'pivotal-sprout/sprout-ssh'

cookbook 'sprout-build-automation',
  :git => 'http://github.cerner.com/tb021781/sprout-build-automation.git',
  :ref => 'cleanup'
